name: ci-golang-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    env:
      GOMODCACHE: ""
      GOCACHE: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: 
          go-version: 1.22.2
          cache: false
      - run: go test .
        working-directory: ./continuous-integration/code
      - run: go run .
        working-directory: ./continuous-integration/code
