name: ci-golang-workflow
on: [push, pull_request]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    env:
      GOMODCACHE: ""
      GOCACHE: ""
    strategy:
      matrix:
        go-version: [1.22.2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: 
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go test .
        working-directory: ./continuous-integration/code
      - run: go run .
        working-directory: ./continuous-integration/code
