name: ci-golang-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    env:
      GOMODCACHE: ""
      GOCACHE: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: 
          go-version: 1.22.2
      - run: go test ./continuous-integration/code
      - run: go run ./continuous-integration/code
